---

 - name: HAProxy config deployment
   template:
     src: HAProxy-template.j2
     dest: /etc/haproxy/haproxy.cfg

 - name: restart HAProxy
   supervisorctl:
     name: haproxy
     state: restarted
